maintainer        "Jan Andersson"
maintainer_email  "jan.andersson@gmail.com"
license           "MIT"
description       "Install git and configuration"
version           "1.0.0"
supports          "mac_os_x"
