maintainer        "Mynewsdesk"
maintainer_email  "dev@mynewsdesk.com"
license           "MIT"
description       "Enables VI-mode in bash and readline"
version           "1.0.0"
supports          "mac_os_x"
depends           "homebrew"
