package "git"
package "ack"
package "watch"
package "macvim"

include_recipe "homebrew"
include_recipe "pivotal_workstation::alfred"
include_recipe "pivotal_workstation::arq"
include_recipe "pivotal_workstation::java"
include_recipe "pivotal_workstation::chrome"
include_recipe "pivotal_workstation::dropbox"
include_recipe "pivotal_workstation::1password"
