maintainer        "Mynewsdesk"
maintainer_email  "dev@mynewsdesk.com"
license           "MIT"
description       "Install MacVim"
version           "1.0.0"
supports          "mac_os_x"
depends           "homebrew"
