maintainer        "Jan Andersson"
maintainer_email  "jan.andersson@gmail.com"
license           "MIT"
description       "Install some Unix essentials"
version           "1.0.0"
supports          "mac_os_x"
depends           "homebrew"
